<?xml version="1.0" encoding="utf-8"?><Database Name="MainDB" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Branch">
    <Type Name="Branch">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CustomerCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Customer_Branch" Member="Customer" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Customer">
    <Type Name="Customer">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="FAX" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ContactPerson" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Logo" Type="System.Data.Linq.Binary" DbType="Binary(100)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Customer_Branch" Member="Branch" ThisKey="ID" OtherKey="CustomerID" Type="Branch" />
      <Association Name="Customer_CustomerConfig" Member="CustomerConfig" ThisKey="ID" OtherKey="CustomerID" Type="CustomerConfig" />
      <Association Name="Customer_CustomerReport" Member="CustomerReport" ThisKey="ID" OtherKey="CustomerID" Type="CustomerReport" />
    </Type>
  </Table>
  <Table Name="CustomerConfig">
    <Type Name="CustomerConfig">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Customer_CustomerConfig" Member="Customer" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="CustomerReport">
    <Type Name="CustomerReport">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ReportID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Customer_CustomerReport" Member="Customer" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" />
      <Association Name="Report_CustomerReport" Member="Report" ThisKey="ReportID" OtherKey="ID" Type="Report" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Report">
    <Type Name="Report">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="Report_CustomerReport" Member="CustomerReport" ThisKey="ID" OtherKey="ReportID" Type="CustomerReport" />
    </Type>
  </Table>
</Database>